In [ ]:
import numpy as np
# Create a rank 1 array
a = np.array([0, 1, 2])w
print(type(a))
# this will print the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
# Change an element of the array
a[0] = 5
print(a)
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]
(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [ ]:
import numpy as np

In [ ]:
data=np.loadtxt("/content/Untitled0.ipynb",dtype="str")

In [ ]:
data

array(['{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyP78kZADumHSR5cswSYQcDE"},"kernelspec":{"name":"python3","display_name":"Python',
       '3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","source":["import',
       'numpy', 'as', 'np\\n","'], dtype='<U172')